global:
  licenseKey: test-license-key
  cluster: test-cluster

# install everything
infrastructure:
  enabled: true

prometheus:
  enabled: true

webhook:
  enabled: true

ksm:
  enabled: true

kubeEvents:
  enabled: true

logging:
  enabled: true
