name: 'Chart version bumper'
description: 'Bump a Helm chart & app version'
inputs:
  chart_name: 
    description: 'Name of the chart'
    required: true
outputs:
  changes: 
    description: 'The version changes that were made to the chart. Example: `[{field: "appVersion", "from": "1.2", "to": "1.3"}]`'
runs:
  using: 'node12'
  main: 'index.js'