name: Bump Chart Version

on: 
  repository_dispatch:
    types: bump-chart-version

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bump version
        uses: ./.github/actions/chart-version-bumper # Uses an action in the root directory
        id: version-bump
        with:
          chart_name: ${{ github.event.client_payload.chart_name }}
          chart_version: ${{  github.event.client_payload.chart_version }}
          app_version: ${{  github.event.client_payload.app_version }}
      - name: Show changes from bump
        run: echo "The following changes are made to the Chart ${{ steps.version-bump.outputs.changes }}"
      - name: Show git changes 
        run: git diff